param(
  [string]$Target = '.',
  [switch]$Global
)
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot
$TargetPath = if ($Global) {
  [Environment]::GetFolderPath('UserProfile')
}
else {
  Resolve-Target -Target $Target
}

# Codex CLI native surfaces (verified against developers.openai.com/codex):
#   - Custom agents: TOML files in .codex/agents/*.toml
#     (name, description, developer_instructions; optional sandbox_mode)
#   - Project guidance: AGENTS.md at repo root (NOT copied here; the target
#     project should own its own AGENTS.md).
#   - Custom prompts: Markdown files in ~/.codex/prompts/*.md. This legacy,
#     global-only surface exposes commands as /prompts:<name>. It is installed
#     only with -Global because Codex does not discover project-scoped prompts.

$AgentsDir = Join-Path $TargetPath '.codex\agents'
New-Item -ItemType Directory -Path $AgentsDir -Force | Out-Null

function Get-CodexSandboxMode {
  param([string]$Name)
  switch ($Name) {
    'builder'      { return 'workspace-write' }
    'qa'           { return 'workspace-write' }
    'orchestrator' { return 'workspace-write' }  # E2E session artifacts (plan.vN, retro)
    default        { return 'read-only' }
  }
}

function Escape-TomlBasicString {
  param([string]$s)
  return ($s -replace '\\','\\' -replace '"','\"')
}

$genFiles = @()
$agentFiles = @(Get-AgentFiles -Repo $Repo)
$syncCommand = if ($Global) { 'make sync-codex-global' } else { 'make sync-codex TARGET=<dir>' }
foreach ($a in $agentFiles) {
  $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
  $desc = Get-AgentDescription -Path $a.Path
  $sandbox = Get-CodexSandboxMode -Name $a.Name
  $descEsc = Escape-TomlBasicString -s $desc

  $header = "# generated by '$syncCommand'; source: agents/$($a.Name).md" + "`n" +
            "# Do not edit here; edit agents/$($a.Name).md and re-run: $syncCommand"

  $toml = $header + "`n`n" +
          "name = `"$($a.Name)`"" + "`n" +
          "description = `"$descEsc`"" + "`n" +
          "sandbox_mode = `"$sandbox`"" + "`n" +
          "developer_instructions = '''" + "`n" +
          $content + "`n" +
          "'''" + "`n"

  $out = Join-Path $AgentsDir "$($a.Name).toml"
  Set-Content -LiteralPath $out -Value $toml -Encoding utf8 -NoNewline
  $genFiles += $out
}

if ($Global) {
  $PromptsDir = Join-Path $TargetPath '.codex\prompts'
  $SkillsRoot = Join-Path $TargetPath '.agents\skills'
  New-Item -ItemType Directory -Path $PromptsDir -Force | Out-Null
  New-Item -ItemType Directory -Path $SkillsRoot -Force | Out-Null

  foreach ($c in (Get-CommandFiles -Repo $Repo)) {
    $agent = Get-CommandAgent -Path $c.Path
    if (-not $agent) {
      Write-Warning "codex: skipping command '$($c.Name)' because it does not reference an agent"
      continue
    }

    $task = Get-CommandTask -Path $c.Path
    $skillDesc = Get-CommandSkillDescription -Path $c.Path -CommandName $c.Name -AgentName $agent
    $displayName = Get-DisplayAgentName -Name $agent
    $generated = "<!-- generated by ``$syncCommand``; source: commands/$($c.Name).md. Do not edit here; edit the source and re-run ``$syncCommand`` -->"

    if ($c.Name -eq 'e2e' -or $c.Name -eq 'e2e-resume') {
      # Main session IS the orchestrator for these two commands — never spawn a nested
      # orchestrator here either (same Identity rule as the skill-writer's self-run branch).
      $prompt = "---`n" +
                "description: Run this pipeline yourself in the current conversation (do not spawn $displayName)`n" +
                "---`n`n" +
                $generated + "`n`n" +
                "**YOU** run this pipeline in the **current** conversation. Do **not** spawn an ``$agent`` subagent, do not fork a second E2E brain, and do not re-invoke ``/e2e`` or ``/e2e-resume``.`n`n" +
                $task + "`n"
    }
    else {
      $prompt = "---`n" +
                "description: Run the $displayName custom agent for the current request`n" +
                "---`n`n" +
                $generated + "`n`n" +
                "Spawn the ``$agent`` custom agent to handle the current request.`n" +
                "Give it the relevant conversation and repository context plus this task guidance:`n`n" +
                $task + "`n`n" +
                "Wait for the agent to finish, then return its result without redoing its work.`n"
    }

    $out = Join-Path $PromptsDir "$($c.Name).md"
    Set-Content -LiteralPath $out -Value $prompt -Encoding utf8 -NoNewline
    $genFiles += $out

    $skillMention = '$' + $c.Name
    $displayCommand = (Get-Culture).TextInfo.ToTitleCase(($c.Name -replace '-', ' '))
    $shortDesc = $skillDesc
    if ($shortDesc.Length -gt 180) { $shortDesc = $shortDesc.Substring(0, 177) + '...' }

    $skillDir = Join-Path $SkillsRoot $c.Name
    $skillAgentDir = Join-Path $skillDir 'agents'
    New-Item -ItemType Directory -Path $skillAgentDir -Force | Out-Null
    $openaiYaml = "interface:`n" +
                  "  display_name: `"$displayCommand`"`n" +
                  "  short_description: `"$($shortDesc -replace '"','\"')`"`n" +
                  "  default_prompt: `"Use $skillMention to run the $($c.Name) workflow.`"`n"
    $metadataOut = Join-Path $skillAgentDir 'openai.yaml'
    Set-Content -LiteralPath $metadataOut -Value $openaiYaml -Encoding utf8 -NoNewline
    $genFiles += $metadataOut
  }

  $skillFiles = Install-PlaybookSkillsTo `
    -SkillsRoot $SkillsRoot `
    -Repo $Repo `
    -SyncCommand $syncCommand `
    -HarnessLabel 'codex' `
    -Global
  $genFiles += $skillFiles
}

Set-ManifestHarness -Target $TargetPath -Harness 'codex' -Files $genFiles
Write-Host "codex: $($agentFiles.Count) custom agents -> $AgentsDir"
if ($Global) {
  Write-Host "codex: custom prompts -> $PromptsDir (invoke as /prompts:<name>; restart Codex first)"
  Write-Host "codex: personal skills -> $SkillsRoot (invoke as `$<name> or select from the / menu)"
}
else {
  Write-Host "codex: custom prompts are global-only; run this installer with -Global to install them."
}
Write-Host "codex: AGENTS.md not copied; the target project owns its own."
