param([string]$Target = '.')
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot
$TargetPath = Resolve-Target -Target $Target

# Codex CLI native surfaces (verified against developers.openai.com/codex):
#   - Custom agents: TOML files in .codex/agents/*.toml
#     (name, description, developer_instructions; optional sandbox_mode)
#   - Project guidance: AGENTS.md at repo root (NOT copied here; the target
#     project should own its own AGENTS.md).
#   - Slash commands: Codex CLI ships only built-in slash commands; there is
#     no file-based custom command surface, so commands/*.md are NOT installed.
#     To run a playbook command in Codex, paste the command prompt text
#     (see commands/*.md) and ask Codex to spawn the matching custom agent.

$AgentsDir = Join-Path $TargetPath '.codex\agents'
New-Item -ItemType Directory -Path $AgentsDir -Force | Out-Null

function Get-CodexSandboxMode {
  param([string]$Name)
  switch ($Name) {
    'builder' { return 'workspace-write' }
    'qa'      { return 'workspace-write' }
    default   { return 'read-only' }
  }
}

function Escape-TomlBasicString {
  param([string]$s)
  return ($s -replace '\\','\\' -replace '"','\"')
}

$genFiles = @()
foreach ($a in (Get-AgentFiles -Repo $Repo)) {
  $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
  $desc = Get-AgentDescription -Path $a.Path
  $sandbox = Get-CodexSandboxMode -Name $a.Name
  $descEsc = Escape-TomlBasicString -s $desc

  $header = "# generated by 'make sync'; source: agents/$($a.Name).md" + "`n" +
            "# Do not edit here; edit agents/$($a.Name).md and re-run: make sync TARGET=<dir>"

  $toml = $header + "`n`n" +
          "name = `"$($a.Name)`"" + "`n" +
          "description = `"$descEsc`"" + "`n" +
          "sandbox_mode = `"$sandbox`"" + "`n" +
          "developer_instructions = '''" + "`n" +
          $content + "`n" +
          "'''" + "`n"

  $out = Join-Path $AgentsDir "$($a.Name).toml"
  Set-Content -LiteralPath $out -Value $toml -Encoding utf8 -NoNewline
  $genFiles += $out
}

Set-ManifestHarness -Target $TargetPath -Harness 'codex' -Files $genFiles
Write-Host "codex: $($genFiles.Count) custom agents -> $AgentsDir"
Write-Host "codex: no custom-command surface in Codex CLI (built-in slash commands only)."
Write-Host "codex: AGENTS.md not copied; the target project owns its own."
