param()

function Get-AgentFiles {
  param([string]$Repo)
  $d = Join-Path $Repo 'agents'
  if (-not (Test-Path $d)) { return @() }
  Get-ChildItem -LiteralPath $d -Filter *.md | ForEach-Object {
    [pscustomobject]@{ Name = $_.BaseName; Path = $_.FullName }
  }
}

function Get-CommandFiles {
  param([string]$Repo)
  $d = Join-Path $Repo 'commands'
  if (-not (Test-Path $d)) { return @() }
  Get-ChildItem -LiteralPath $d -Filter *.md | ForEach-Object {
    [pscustomobject]@{ Name = $_.BaseName; Path = $_.FullName }
  }
}

function Get-AgentDescription {
  param([string]$Path)
  $lines = Get-Content -LiteralPath $Path
  $inPurpose = $false
  foreach ($l in $lines) {
    if ($l -match '^##\s+Purpose') { $inPurpose = $true; continue }
    if ($inPurpose) {
      $t = $l.Trim()
      if ($t) { return $t }
    }
  }
  foreach ($l in $lines) {
    if ($l -match '^#\s+(.+)') { return $matches[1].Trim() }
  }
  return (Split-Path $Path -Leaf)
}

function Get-CommandAgent {
  param([string]$Path)
  $c = Get-Content -Raw -LiteralPath $Path
  if ($c -match 'Use\s+`agents/([^`/]+)\.md`') { return $matches[1] }
  return $null
}

function Get-DisplayAgentName {
  param([string]$Name)
  if ([string]::IsNullOrWhiteSpace($Name)) { return 'agent' }
  if ($Name.Length -le 2) { return $Name.ToUpper() }
  return $Name.Substring(0, 1).ToUpper() + $Name.Substring(1)
}

function Get-OpenCodeAgentMeta {
  param([string]$Name)
  $table = @{
    refiner      = @{ mode = 'subagent'; permission = [ordered]@{ read = 'deny'; edit = 'deny'; bash = 'deny'; websearch = 'deny'; webfetch = 'deny' } }
    planner      = @{ mode = 'primary';  permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
    builder      = @{ mode = 'primary';  permission = [ordered]@{ edit = 'allow'; bash = 'allow' } }
    reviewer     = @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
    qa           = @{ mode = 'subagent'; permission = [ordered]@{ read = 'deny'; edit = 'deny'; bash = 'allow' } }
    curator      = @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
    orchestrator = @{ mode = 'primary';  permission = [ordered]@{ edit = 'deny'; bash = 'ask'; task = 'allow' } }
  }
  if ($table.ContainsKey($Name)) { return $table[$Name] }
  return @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
}

function New-GeneratedComment {
  param([string]$Source)
  $t = '<!-- generated by `make sync`; source: {SRC}. Do not edit here; edit the source and re-run: make sync -->'
  return ($t -replace '\{SRC\}', $Source)
}

function Resolve-Target {
  param([string]$Target)
  if ([string]::IsNullOrWhiteSpace($Target) -or $Target -eq '.') { return (Get-Location).Path }
  $p = Resolve-Path -LiteralPath $Target -ErrorAction SilentlyContinue
  if (-not $p) { New-Item -ItemType Directory -Path $Target -Force | Out-Null; $p = Resolve-Path -LiteralPath $Target }
  return $p.Path
}

function Normalize-Path {
  param([string]$Path)
  return ($Path.TrimEnd('\', '/'))
}

function Get-ManifestPath {
  param([string]$Target)
  return (Join-Path $Target '.agents-sync\manifest.json')
}

function Read-Manifest {
  param([string]$Target)
  $mp = Get-ManifestPath -Target $Target
  if (-not (Test-Path $mp)) { return @() }
  $data = Get-Content -Raw -LiteralPath $mp | ConvertFrom-Json
  if (-not $data) { return @() }
  return @($data)
}

function Write-Manifest {
  param([string]$Target, $Entries)
  $dir = Join-Path $Target '.agents-sync'
  New-Item -ItemType Directory -Path $dir -Force | Out-Null
  $mp = Join-Path $dir 'manifest.json'
  ,$Entries | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $mp -Encoding utf8
}

function Set-ManifestHarness {
  param([string]$Target, [string]$Harness, [string[]]$Files)
  $rest = @((Read-Manifest -Target $Target) | Where-Object { $_.harness -ne $Harness })
  $rest += [pscustomobject]@{ harness = $Harness; files = @($Files) }
  Write-Manifest -Target $Target -Entries $rest
}

function Remove-EmptyParents {
  param([string]$Path, [string]$StopRoot)
  $stop = Normalize-Path -Path $StopRoot
  $p = Split-Path $Path -Parent
  while ($p) {
    $cur = Normalize-Path -Path $p
    if ($stop -and $cur -eq $stop) { break }
    if (-not (Test-Path -LiteralPath $p)) { break }
    $items = Get-ChildItem -LiteralPath $p -Force -ErrorAction SilentlyContinue
    if (($items | Measure-Object).Count -eq 0) {
      Remove-Item -LiteralPath $p -Force
      $p = Split-Path $p -Parent
    }
    else { break }
  }
}

function Clear-ManifestHarness {
  param([string]$Target, [string]$Harness)
  $all = @(Read-Manifest -Target $Target)
  $entry = $all | Where-Object { $_.harness -eq $Harness }
  $rest = @($all | Where-Object { $_.harness -ne $Harness })
  if ($entry) {
    foreach ($f in @($entry.files)) {
      if (Test-Path -LiteralPath $f) {
        Remove-Item -LiteralPath $f -Force
        Remove-EmptyParents -Path $f -StopRoot $Target
      }
    }
  }
  if (($rest | Measure-Object).Count -eq 0) {
    $mp = Get-ManifestPath -Target $Target
    if (Test-Path $mp) {
      Remove-Item -LiteralPath $mp -Force
      Remove-EmptyParents -Path $mp -StopRoot $Target
    }
  }
  else {
    Write-Manifest -Target $Target -Entries $rest
  }
}

function Get-RepoRoot {
  return (Split-Path $PSScriptRoot -Parent)
}
