param()

function Get-AgentFiles {
  param([string]$Repo)
  $d = Join-Path $Repo 'agents'
  if (-not (Test-Path $d)) { return @() }
  Get-ChildItem -LiteralPath $d -Filter *.md | ForEach-Object {
    [pscustomobject]@{ Name = $_.BaseName; Path = $_.FullName }
  }
}

function Get-CommandFiles {
  param([string]$Repo)
  $d = Join-Path $Repo 'commands'
  if (-not (Test-Path $d)) { return @() }
  Get-ChildItem -LiteralPath $d -Filter *.md | ForEach-Object {
    [pscustomobject]@{ Name = $_.BaseName; Path = $_.FullName }
  }
}

function Get-AgentDescription {
  param([string]$Path)
  $lines = Get-Content -LiteralPath $Path
  $inPurpose = $false
  foreach ($l in $lines) {
    if ($l -match '^##\s+Purpose') { $inPurpose = $true; continue }
    if ($inPurpose) {
      $t = $l.Trim()
      if ($t) { return $t }
    }
  }
  foreach ($l in $lines) {
    if ($l -match '^#\s+(.+)') { return $matches[1].Trim() }
  }
  return (Split-Path $Path -Leaf)
}

function Get-CommandAgent {
  param([string]$Path)
  $c = Get-Content -Raw -LiteralPath $Path
  if ($c -match 'Use\s+`agents/([^`/]+)\.md`') { return $matches[1] }
  return $null
}

function Get-DisplayAgentName {
  param([string]$Name)
  if ([string]::IsNullOrWhiteSpace($Name)) { return 'agent' }
  if ($Name.Length -le 2) { return $Name.ToUpper() }
  return $Name.Substring(0, 1).ToUpper() + $Name.Substring(1)
}

function Get-OpenCodeAgentMeta {
  param([string]$Name)
  $table = @{
    refiner      = @{ mode = 'subagent'; permission = [ordered]@{ read = 'deny'; edit = 'deny'; bash = 'deny'; websearch = 'deny'; webfetch = 'deny' } }
    planner      = @{ mode = 'primary';  permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
    builder      = @{ mode = 'primary';  permission = [ordered]@{ edit = 'allow'; bash = 'allow' } }
    reviewer     = @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
    # Stage 6 black-box QA: docs must be readable (no read deny); product write denied; bash for CLI/app.
    # Product-source path deny is policy in agents/qa.md when harness cannot express path-class deny.
    qa           = @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'allow' } }
    curator      = @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
    sensei       = @{ mode = 'subagent'; permission = [ordered]@{ read = 'deny'; edit = 'deny'; bash = 'deny'; websearch = 'deny'; webfetch = 'deny' } }
    # Docs-only policy (agents/advisor.md): may read; no edit/bash/web exploration of implementation.
    advisor      = @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'deny'; websearch = 'deny'; webfetch = 'deny' } }
    # Orchestrator may write E2E session artifacts (plans, retro) and spawn specialists.
    orchestrator = @{ mode = 'primary';  permission = [ordered]@{ edit = 'allow'; bash = 'ask'; task = 'allow' } }
  }
  if ($table.ContainsKey($Name)) { return $table[$Name] }
  return @{ mode = 'subagent'; permission = [ordered]@{ edit = 'deny'; bash = 'ask' } }
}

function New-GeneratedComment {
  param([string]$Source)
  $t = '<!-- generated by `make sync`; source: {SRC}. Do not edit here; edit the source and re-run: make sync -->'
  return ($t -replace '\{SRC\}', $Source)
}

function Resolve-Target {
  param([string]$Target)
  if ([string]::IsNullOrWhiteSpace($Target) -or $Target -eq '.') { return (Get-Location).Path }
  $p = Resolve-Path -LiteralPath $Target -ErrorAction SilentlyContinue
  if (-not $p) { New-Item -ItemType Directory -Path $Target -Force | Out-Null; $p = Resolve-Path -LiteralPath $Target }
  return $p.Path
}

function Normalize-Path {
  param([string]$Path)
  return ($Path.TrimEnd('\', '/'))
}

function Get-ManifestPath {
  param([string]$Target)
  return (Join-Path $Target '.agents-sync\manifest.json')
}

function Read-Manifest {
  param([string]$Target)
  $mp = Get-ManifestPath -Target $Target
  if (-not (Test-Path $mp)) { return @() }
  $data = Get-Content -Raw -LiteralPath $mp | ConvertFrom-Json
  if (-not $data) { return @() }
  return @($data)
}

function Write-Manifest {
  param([string]$Target, $Entries)
  $dir = Join-Path $Target '.agents-sync'
  New-Item -ItemType Directory -Path $dir -Force | Out-Null
  $mp = Join-Path $dir 'manifest.json'
  ,$Entries | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $mp -Encoding utf8
}

function Set-ManifestHarness {
  param([string]$Target, [string]$Harness, [string[]]$Files)
  $rest = @((Read-Manifest -Target $Target) | Where-Object { $_.harness -ne $Harness })
  $rest += [pscustomobject]@{ harness = $Harness; files = @($Files) }
  Write-Manifest -Target $Target -Entries $rest
}

function Remove-EmptyParents {
  param([string]$Path, [string]$StopRoot)
  $stop = Normalize-Path -Path $StopRoot
  $p = Split-Path $Path -Parent
  while ($p) {
    $cur = Normalize-Path -Path $p
    if ($stop -and $cur -eq $stop) { break }
    if (-not (Test-Path -LiteralPath $p)) { break }
    $items = Get-ChildItem -LiteralPath $p -Force -ErrorAction SilentlyContinue
    if (($items | Measure-Object).Count -eq 0) {
      Remove-Item -LiteralPath $p -Force
      $p = Split-Path $p -Parent
    }
    else { break }
  }
}

function Clear-ManifestHarness {
  param([string]$Target, [string]$Harness)
  $all = @(Read-Manifest -Target $Target)
  $entry = $all | Where-Object { $_.harness -eq $Harness }
  $rest = @($all | Where-Object { $_.harness -ne $Harness })
  if ($entry) {
    foreach ($f in @($entry.files)) {
      if (Test-Path -LiteralPath $f) {
        Remove-Item -LiteralPath $f -Force
        Remove-EmptyParents -Path $f -StopRoot $Target
      }
    }
  }
  if (($rest | Measure-Object).Count -eq 0) {
    $mp = Get-ManifestPath -Target $Target
    if (Test-Path $mp) {
      Remove-Item -LiteralPath $mp -Force
      Remove-EmptyParents -Path $mp -StopRoot $Target
    }
  }
  else {
    Write-Manifest -Target $Target -Entries $rest
  }
}

function Get-RepoRoot {
  return (Split-Path $PSScriptRoot -Parent)
}

function Get-CommandTask {
  param([string]$Path)
  $content = Get-Content -Raw -LiteralPath $Path
  $match = [regex]::Match($content, '(?ms)Prompt:\s*```text\s*\r?\n(.*?)\r?\n```')
  if ($match.Success) { return $match.Groups[1].Value.Trim() }
  return $content.Trim()
}

function Get-CommandSkillDescription {
  param([string]$Path, [string]$CommandName, [string]$AgentName)
  $content = Get-Content -Raw -LiteralPath $Path
  $skillDescMatch = [regex]::Match($content, '(?m)^Skill-Description:\s*(.+)$')
  if ($skillDescMatch.Success) { return $skillDescMatch.Groups[1].Value.Trim() }
  $display = Get-DisplayAgentName -Name $AgentName
  return "Delegate the current request to the $display custom agent. Use when the user invokes `$$CommandName or asks to run the $CommandName workflow."
}

function New-PlaybookSkillMarkdown {
  param(
    [string]$CommandName,
    [string]$AgentName,
    [string]$Task,
    [string]$SkillDescription,
    [string]$SyncCommand,
    [string]$Repo
  )
  $agentsSourceDir = Join-Path $Repo 'agents'
  $agentSourcePath = Join-Path $agentsSourceDir "$AgentName.md"
  $generated = "<!-- generated by ``$SyncCommand``; source: commands/$CommandName.md. Do not edit here; edit the source and re-run ``$SyncCommand`` -->"

  if ($CommandName -eq 'e2e' -or $CommandName -eq 'e2e-resume') {
    # Main session IS the orchestrator — never nest another orchestrator (context loss).
    # Applies to both the fresh pipeline (/e2e) and re-entry into a stopped session (/e2e-resume):
    # both run in the main conversation under the same identity rule.
    $skillBody = @"
# /$CommandName — main agent is the Orchestrator

**YOU** run this pipeline in the **current** conversation. Do **not** spawn an ``orchestrator`` subagent, do not fork a second E2E brain, and do not re-invoke ``/e2e`` or ``/e2e-resume``.

1. Load and follow the orchestrator playbook yourself:
   - ``$agentSourcePath``
   - Specialists directory: ``$agentsSourceDir``
2. Execute the task guidance below as that Orchestrator (full E2E pipeline, resuming from the reconstructed state when invoked as /e2e-resume).
3. Spawn **only** leaf specialists when needed: ``refiner``, ``planner``, ``sensei``, ``advisor``, ``builder``, ``reviewer``, ``curator``, ``qa``.
4. Preserve the same Sensei/Advisor/Reviewer threads across review iterations (resume; do not reset).
5. Apply Correctness over delivery convenience; you write plan revisions after v0 yourself.

## Task guidance

$Task
"@
  }
  else {
    $skillBody = @"
Spawn the ``$AgentName`` custom agent / subagent to handle the current request when the harness supports named agents.
Give it the relevant conversation and repository context plus this task guidance:

$Task

If the harness cannot spawn a named ``$AgentName`` agent, **you** must load and follow the canonical agent file and execute that role yourself:
- Agent source: ``$agentSourcePath``
- Related agents directory: ``$agentsSourceDir``

When you are already acting as orchestrator (e.g. mid-``/e2e``), do **not** spawn another orchestrator — only leaf specialists (refiner, planner, sensei, advisor, builder, reviewer, curator, qa). Preserve the same Sensei/Advisor/Reviewer threads across review iterations (resume; do not reset). Wait for each specialist step to finish before applying its output; do not redo specialist work with weaker judgment.

Apply Correctness over delivery convenience when the target project defines it: complete and durable work over velocity shortcuts.
"@
  }
  return "---`n" +
         "name: $CommandName`n" +
         "description: $SkillDescription`n" +
         "---`n`n" +
         $generated + "`n`n" +
         $skillBody + "`n"
}

function Get-ClaudeAgentFrontmatter {
  param([string]$Name, [string]$Description)
  # tools / model tuned for Claude Code subagent frontmatter
  $meta = switch ($Name) {
    'orchestrator' {
      @{
        tools = 'Agent, Read, Write, Edit, Grep, Glob, Bash, Skill'
        model = 'opus'
        permissionMode = 'acceptEdits'
      }
    }
    'planner' {
      @{
        tools = 'Read, Grep, Glob, Bash'
        model = 'opus'
        permissionMode = 'plan'
      }
    }
    'sensei' {
      @{
        tools = ''  # no tools — judgment from provided context only
        model = 'opus'
        disallowedTools = 'Read, Write, Edit, Bash, Grep, Glob, WebFetch, WebSearch'
      }
    }
    'advisor' {
      @{
        # Read/Grep/Glob for documentation & contracts only — policy in agents/advisor.md forbids source.
        tools = 'Read, Grep, Glob'
        model = 'sonnet'
        # Block write/shell so Advisor cannot "just check" by running or editing code.
        disallowedTools = 'Write, Edit, Bash, NotebookEdit, WebFetch, WebSearch'
      }
    }
    'builder' {
      @{
        tools = 'Read, Write, Edit, Grep, Glob, Bash'
        model = 'sonnet'
        permissionMode = 'acceptEdits'
        # Note: long/integration tests are policy-forbidden in builder.md (orchestrator runs them).
      }
    }
    'reviewer' {
      @{
        tools = 'Read, Grep, Glob, Bash'
        model = 'sonnet'
      }
    }
    'refiner' {
      @{
        tools = ''
        model = 'sonnet'
        disallowedTools = 'Read, Write, Edit, Bash, Grep, Glob, WebFetch, WebSearch'
      }
    }
    'qa' {
      @{
        # Stage 6: may read docs + run app; must not write product or notebooks.
        # Product-source oracle forbid is policy in agents/qa.md (degraded detect if needed).
        tools = 'Bash, Read, Grep, Glob'
        model = 'sonnet'
        disallowedTools = 'Write, Edit, NotebookEdit'
      }
    }
    'curator' {
      @{
        tools = 'Read, Grep, Glob'
        model = 'sonnet'
      }
    }
    default {
      @{
        tools = 'Read, Grep, Glob, Bash'
        model = 'inherit'
      }
    }
  }
  $lines = @(
    '---'
    "name: $Name"
    "description: $($Description -replace '"', '''')"
  )
  if ($meta.tools) { $lines += "tools: $($meta.tools)" }
  if ($meta.disallowedTools) { $lines += "disallowedTools: $($meta.disallowedTools)" }
  if ($meta.model) { $lines += "model: $($meta.model)" }
  if ($meta.permissionMode) { $lines += "permissionMode: $($meta.permissionMode)" }
  $lines += '---'
  return ($lines -join "`n")
}

function Install-PlaybookSkillsTo {
  param(
    [string]$SkillsRoot,
    [string]$Repo,
    [string]$SyncCommand,
    [string]$HarnessLabel
  )
  New-Item -ItemType Directory -Path $SkillsRoot -Force | Out-Null
  $genFiles = @()
  foreach ($c in (Get-CommandFiles -Repo $Repo)) {
    $agent = Get-CommandAgent -Path $c.Path
    if (-not $agent) {
      Write-Warning "$HarnessLabel`: skipping command '$($c.Name)' (no agent reference)"
      continue
    }
    $task = Get-CommandTask -Path $c.Path
    $skillDesc = Get-CommandSkillDescription -Path $c.Path -CommandName $c.Name -AgentName $agent
    $skill = New-PlaybookSkillMarkdown `
      -CommandName $c.Name `
      -AgentName $agent `
      -Task $task `
      -SkillDescription $skillDesc `
      -SyncCommand $SyncCommand `
      -Repo $Repo

    $skillDir = Join-Path $SkillsRoot $c.Name
    New-Item -ItemType Directory -Path $skillDir -Force | Out-Null
    $skillOut = Join-Path $skillDir 'SKILL.md'
    Set-Content -LiteralPath $skillOut -Value $skill -Encoding utf8 -NoNewline
    $genFiles += $skillOut
  }
  return $genFiles
}
