param(
  [string]$Target = '.',
  [switch]$Global
)
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot

# Grok Build / Grok TUI skills:
#   Personal:  ~/.grok/skills/<name>/SKILL.md
#   Project:   <target>/.grok/skills/<name>/SKILL.md
# Same SKILL.md shape as Claude / Codex agent skills (YAML frontmatter + body).

if ($Global) {
  $SkillsRoot = Join-Path ([Environment]::GetFolderPath('UserProfile')) '.grok\skills'
  $syncCommand = 'make sync-grok-global'
  $manifestTarget = Join-Path ([Environment]::GetFolderPath('UserProfile')) '.grok'
}
else {
  $TargetPath = Resolve-Target -Target $Target
  $SkillsRoot = Join-Path $TargetPath '.grok\skills'
  $syncCommand = 'make sync-grok TARGET=<dir>'
  $manifestTarget = $TargetPath
}

$genFiles = Install-PlaybookSkillsTo `
  -SkillsRoot $SkillsRoot `
  -Repo $Repo `
  -SyncCommand $syncCommand `
  -HarnessLabel 'grok' `
  -Global:$Global

# Optional: copy agent markdown under skills/_agents for local reference (not auto-loaded by Grok)
$agentsRef = Join-Path $SkillsRoot '_playbook-agents'
New-Item -ItemType Directory -Path $agentsRef -Force | Out-Null
foreach ($a in (Get-AgentFiles -Repo $Repo)) {
  $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
  $header = "<!-- generated by ``$syncCommand``; source: agents/$($a.Name).md -->"
  $out = Join-Path $agentsRef "$($a.Name).md"
  Set-Content -LiteralPath $out -Value "$header`n`n$content`n" -Encoding utf8 -NoNewline
  $genFiles += $out
}

Set-ManifestHarness -Target $manifestTarget -Harness 'grok' -Files $genFiles
$cmdCount = @(Get-CommandFiles -Repo $Repo).Count
Write-Host "grok: $cmdCount skills -> $SkillsRoot"
Write-Host "grok: agent references -> $agentsRef"
if ($Global) {
  Write-Host "grok: personal install complete. Skills appear as /e2e, /plan-this, etc. after reload."
}
