param([string]$Target = '.')
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot

if ([string]::IsNullOrWhiteSpace($Target) -or $Target -eq '.') {
  $TargetPath = $Repo
}
else {
  $tp = Resolve-Path -LiteralPath $Target -ErrorAction SilentlyContinue
  if ($tp -and ((Normalize-Path -Path $tp.Path) -eq (Normalize-Path -Path $Repo))) {
    $TargetPath = $Repo
  }
  else {
    Write-Error "opencode install is in-repo only (target must be this repo). For other opencode projects, add this repo as a 'reference' (see adapters/opencode.md)."
    exit 1
  }
}

$OcDir = Join-Path $TargetPath '.opencode'
$CmdDir = Join-Path $OcDir 'commands'
New-Item -ItemType Directory -Path $OcDir -Force | Out-Null
New-Item -ItemType Directory -Path $CmdDir -Force | Out-Null

$agents = Get-AgentFiles -Repo $Repo | Sort-Object Name
$commands = Get-CommandFiles -Repo $Repo | Sort-Object Name

# 5.1 (F-7): permission.task identity block, derived from Get-RoleMeta's frozen
# `opencodeTaskPolicy` field — never hand-picked here. Leaf role names are
# discovered from the real agents/*.md set (not a hardcoded literal list), so a
# 10th role added later via the amendment protocol is picked up automatically
# instead of silently omitted. Every entry is explicit allow/deny; no wildcard
# key is used for the orchestrator's own list, removing the load-bearing
# key-ordering fragility a wildcard-first design would have.
$leafRoleNames = @($agents.Name | Where-Object { (Get-RoleMeta -Name $_).opencodeTaskPolicy -eq 'leaf' })

# 5.2 (F-6): model/temperature, derived from Get-RoleMeta's frozen `tier` field.
# Model values reuse this repo's own existing tier-alias convention (the same
# `opus`/`sonnet` strings install/claude.ps1 already emits) rather than a
# literal provider-qualified model id, which this session could not verify
# against OpenCode's exact resolution scheme (no network access from this
# role) — see adapters/opencode.md and plan.v3.md open decision #6.
function Get-OpenCodeModelForTier {
  param([string]$Tier)
  if ($Tier -eq 'Highest') { return 'opus' }
  return 'sonnet'
}
# Explicit list per task 5.2 — analysis/judgment roles get low temperature so
# review output stays deterministic; generation/action roles keep default.
$analysisRoles = @('sensei', 'advisor', 'planner', 'reviewer')
$analysisTemperature = 0.1

$agentObj = [ordered]@{}
foreach ($a in $agents) {
  $desc = Get-AgentDescription -Path $a.Path
  $meta = Get-OpenCodeAgentMeta -Name $a.Name
  $roleMeta = Get-RoleMeta -Name $a.Name

  $perm = [ordered]@{}
  foreach ($k in $meta.permission.Keys) { $perm[$k] = $meta.permission[$k] }
  if ($roleMeta.opencodeTaskPolicy -eq 'orchestrator') {
    $taskAllow = [ordered]@{}
    foreach ($n in $leafRoleNames) { $taskAllow[$n] = 'allow' }
    $perm['task'] = $taskAllow
  }
  else {
    $perm['task'] = [ordered]@{ '*' = 'deny' }
  }

  $entry = [ordered]@{
    description = $desc
    mode        = $meta.mode
    model       = (Get-OpenCodeModelForTier -Tier $roleMeta.tier)
  }
  if ($analysisRoles -contains $a.Name) { $entry['temperature'] = $analysisTemperature }
  $entry['permission'] = $perm
  $entry['prompt'] = "{file:../agents/$($a.Name).md}"
  $agentObj[$a.Name] = $entry
}

$config = [ordered]@{
  '$schema'    = 'https://opencode.ai/config.json'
  agent        = $agentObj
}

$json = $config | ConvertTo-Json -Depth 10
$cfgPath = Join-Path $OcDir 'opencode.json'
if ((Test-Path -LiteralPath $cfgPath) -and -not (Test-Path -LiteralPath "$cfgPath.bak")) {
  Copy-Item -LiteralPath $cfgPath -Destination "$cfgPath.bak"
}
Set-Content -LiteralPath $cfgPath -Value $json -Encoding utf8

$genFiles = @($cfgPath)

foreach ($c in $commands) {
  $agent = Get-CommandAgent -Path $c.Path
  if (-not $agent) { continue }
  $display = Get-DisplayAgentName -Name $agent
  # 5.3: /e2e and /e2e-resume must run as the main agent (identity rule — a
  # nested orchestrator loses context); every other command is a leaf and is
  # safe to run as an OpenCode subtask.
  $isPrimaryContext = ($c.Name -eq 'e2e' -or $c.Name -eq 'e2e-resume')
  $subtaskLine = if ($isPrimaryContext) { '' } else { "subtask: true`n" }
  $body = @'
---
# generated by `make install-opencode`; source: commands/{CMD}.md
description: Run the {DISPLAY}.
agent: {AGENT}
{SUBTASK}---
@commands/{CMD}.md
'@ -replace '\{CMD\}', $c.Name -replace '\{DISPLAY\}', $display -replace '\{AGENT\}', $agent -replace '\{SUBTASK\}', $subtaskLine
  $body = $body + "`n"
  $cpath = Join-Path $CmdDir "$($c.Name).md"
  Set-Content -LiteralPath $cpath -Value $body -Encoding utf8 -NoNewline
  $genFiles += $cpath
}

Set-ManifestHarness -Target $TargetPath -Harness 'opencode' -Files $genFiles
Write-Host "opencode: $($agents.Count) agents, $($commands.Count) commands -> $OcDir"
Write-Host "opencode: agents reference ../agents/*.md via {file:...}; commands reference @commands/*.md"
Write-Host "opencode: restart opencode to load."
