param([string]$Target = '.')
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot

if ([string]::IsNullOrWhiteSpace($Target) -or $Target -eq '.') {
  $TargetPath = $Repo
}
else {
  $tp = Resolve-Path -LiteralPath $Target -ErrorAction SilentlyContinue
  if ($tp -and ((Normalize-Path -Path $tp.Path) -eq (Normalize-Path -Path $Repo))) {
    $TargetPath = $Repo
  }
  else {
    Write-Error "opencode install is in-repo only (target must be this repo). For other opencode projects, add this repo as a 'reference' (see adapters/opencode.md)."
    exit 1
  }
}

$OcDir = Join-Path $TargetPath '.opencode'
$CmdDir = Join-Path $OcDir 'commands'
New-Item -ItemType Directory -Path $OcDir -Force | Out-Null
New-Item -ItemType Directory -Path $CmdDir -Force | Out-Null

$agents = Get-AgentFiles -Repo $Repo | Sort-Object Name
$commands = Get-CommandFiles -Repo $Repo | Sort-Object Name

$agentObj = [ordered]@{}
foreach ($a in $agents) {
  $desc = Get-AgentDescription -Path $a.Path
  $meta = Get-OpenCodeAgentMeta -Name $a.Name
  $perm = [ordered]@{}
  foreach ($k in $meta.permission.Keys) { $perm[$k] = $meta.permission[$k] }
  $agentObj[$a.Name] = [ordered]@{
    description = $desc
    mode        = $meta.mode
    permission  = $perm
    prompt      = "{file:../agents/$($a.Name).md}"
  }
}

$config = [ordered]@{
  '$schema'    = 'https://opencode.ai/config.json'
  agent        = $agentObj
}

$json = $config | ConvertTo-Json -Depth 10
$cfgPath = Join-Path $OcDir 'opencode.json'
if ((Test-Path -LiteralPath $cfgPath) -and -not (Test-Path -LiteralPath "$cfgPath.bak")) {
  Copy-Item -LiteralPath $cfgPath -Destination "$cfgPath.bak"
}
Set-Content -LiteralPath $cfgPath -Value $json -Encoding utf8

$genFiles = @($cfgPath)

foreach ($c in $commands) {
  $agent = Get-CommandAgent -Path $c.Path
  if (-not $agent) { continue }
  $display = Get-DisplayAgentName -Name $agent
  $body = @'
---
# generated by `make install-opencode`; source: commands/{CMD}.md
description: Run the {DISPLAY}.
agent: {AGENT}
---
@commands/{CMD}.md
'@ -replace '\{CMD\}', $c.Name -replace '\{DISPLAY\}', $display -replace '\{AGENT\}', $agent
  $body = $body + "`n"
  $cpath = Join-Path $CmdDir "$($c.Name).md"
  Set-Content -LiteralPath $cpath -Value $body -Encoding utf8 -NoNewline
  $genFiles += $cpath
}

Set-ManifestHarness -Target $TargetPath -Harness 'opencode' -Files $genFiles
Write-Host "opencode: $($agents.Count) agents, $($commands.Count) commands -> $OcDir"
Write-Host "opencode: agents reference ../agents/*.md via {file:...}; commands reference @commands/*.md"
Write-Host "opencode: restart opencode to load."
