param()
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot

<#
  make verify-sync (D12, task 1.6) — drift detector for the four PERSONAL
  ("-Global") harness projections: ~/.claude, ~/.grok, ~/.codex, ~/.agents
  (Codex's global skills root). Regenerates each harness's expected file set
  into an isolated temp root, diffs it against the live tree, and prints
  IN SYNC / DRIFT / NOT INSTALLED per root. Exits non-zero iff any root shows
  real DRIFT. Strictly read-only w.r.t. the operator's home (I5): every write
  in this script targets the temp root only; live trees are only ever read.

  Why this script re-derives each harness's Global output instead of shelling
  out to claude.ps1/grok.ps1/codex.ps1 -Global (which would be more DRY): on
  Windows, [Environment]::GetFolderPath('UserProfile') resolves via the OS
  profile registry, not the USERPROFILE env var — verified empirically (a
  child process launched with USERPROFILE overridden still reports the real
  profile path). There is no supported way to redirect a -Global installer's
  root to a temp directory from the outside, and install/<harness>.ps1 are
  each owned by a later wave (plan.v3.md section 1.4a) so wave-1 cannot
  restructure them to accept an override parameter. The functions below
  therefore mirror each installer's current Global-mode body construction
  using the SAME shared common.ps1 primitives those installers call — only
  the harness-specific glue (folder layout, TOML/prompt assembly) is
  duplicated. If a later wave changes that glue, this file must be updated in
  lockstep; that coupling is intentional and disclosed, not hidden.
#>

function Get-CodexSandboxModeMirror {
  # Mirrors install/codex.ps1's Get-CodexSandboxMode (wave-3-owned).
  param([string]$Name)
  switch ($Name) {
    'builder'      { return 'workspace-write' }
    'qa'           { return 'workspace-write' }
    'orchestrator' { return 'workspace-write' }
    default        { return 'read-only' }
  }
}

function Escape-TomlBasicStringMirror {
  # Mirrors install/codex.ps1's Escape-TomlBasicString (wave-3-owned).
  param([string]$s)
  return ($s -replace '\\', '\\' -replace '"', '\"')
}

function Build-ClaudeGlobalExpectedTree {
  # Mirrors install/claude.ps1's -Global branch (wave-2-owned).
  param([string]$Repo, [string]$Root)
  $syncCommand = 'make sync-claude-global'
  $agentsDir = Join-Path $Root 'agents'
  $cmdsDir = Join-Path $Root 'commands'
  $skillsRoot = Join-Path $Root 'skills'
  New-Item -ItemType Directory -Path $agentsDir, $cmdsDir, $skillsRoot -Force | Out-Null

  foreach ($a in (Get-AgentFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
    $desc = Get-AgentDescription -Path $a.Path
    $header = "<!-- generated by ``$syncCommand``; source: agents/$($a.Name).md. Do not edit here; edit agents/$($a.Name).md and re-run: $syncCommand -->"
    $fm = Get-ClaudeAgentFrontmatter -Name $a.Name -Description $desc
    $body = "$fm`n`n$header`n`n$content`n"
    Set-Content -LiteralPath (Join-Path $agentsDir "$($a.Name).md") -Value $body -Encoding utf8 -NoNewline
  }

  foreach ($c in (Get-CommandFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $c.Path).TrimEnd()
    $header = "<!-- generated by ``$syncCommand``; source: commands/$($c.Name).md -->"
    $agent = Get-CommandAgent -Path $c.Path
    $task = Get-CommandTask -Path $c.Path
    $agentForDesc = if ($agent) { $agent } else { 'agent' }
    $skillDesc = Get-CommandSkillDescription -Path $c.Path -CommandName $c.Name -AgentName $agentForDesc
    $agentsSourceDir = Join-Path $Repo 'agents'
    $cmdBody = @"
---
description: $skillDesc
---

$header

$task

Load specialist prompts from ``$agentsSourceDir`` as needed. Prefer the installed skill ``/$($c.Name)`` and subagents under the Claude agents directory when available.
"@
    Set-Content -LiteralPath (Join-Path $cmdsDir "$($c.Name).md") -Value $cmdBody -Encoding utf8 -NoNewline
  }

  Install-PlaybookSkillsTo -SkillsRoot $skillsRoot -Repo $Repo -SyncCommand $syncCommand -HarnessLabel 'claude' -Global | Out-Null
}

function Build-GrokGlobalExpectedTree {
  # Mirrors install/grok.ps1's -Global branch (wave-5-owned).
  param([string]$Repo, [string]$Root)
  $syncCommand = 'make sync-grok-global'
  $skillsRoot = Join-Path $Root 'skills'
  New-Item -ItemType Directory -Path $skillsRoot -Force | Out-Null
  Install-PlaybookSkillsTo -SkillsRoot $skillsRoot -Repo $Repo -SyncCommand $syncCommand -HarnessLabel 'grok' -Global | Out-Null

  $agentsRef = Join-Path $skillsRoot '_playbook-agents'
  New-Item -ItemType Directory -Path $agentsRef -Force | Out-Null
  foreach ($a in (Get-AgentFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
    $header = "<!-- generated by ``$syncCommand``; source: agents/$($a.Name).md -->"
    Set-Content -LiteralPath (Join-Path $agentsRef "$($a.Name).md") -Value "$header`n`n$content`n" -Encoding utf8 -NoNewline
  }
}

function Build-CodexGlobalExpectedTrees {
  # Mirrors install/codex.ps1's -Global branch (wave-3-owned).
  param([string]$Repo, [string]$CodexRoot, [string]$AgentsRoot)
  $syncCommand = 'make sync-codex-global'
  $agentsDir = Join-Path $CodexRoot 'agents'
  $promptsDir = Join-Path $CodexRoot 'prompts'
  $skillsRoot = Join-Path $AgentsRoot 'skills'
  New-Item -ItemType Directory -Path $agentsDir, $promptsDir, $skillsRoot -Force | Out-Null

  foreach ($a in (Get-AgentFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
    $desc = Get-AgentDescription -Path $a.Path
    $sandbox = Get-CodexSandboxModeMirror -Name $a.Name
    $descEsc = Escape-TomlBasicStringMirror -s $desc
    $header = "# generated by '$syncCommand'; source: agents/$($a.Name).md" + "`n" +
              "# Do not edit here; edit agents/$($a.Name).md and re-run: $syncCommand"
    $toml = $header + "`n`n" +
            "name = `"$($a.Name)`"" + "`n" +
            "description = `"$descEsc`"" + "`n" +
            "sandbox_mode = `"$sandbox`"" + "`n" +
            "developer_instructions = '''" + "`n" +
            $content + "`n" +
            "'''" + "`n"
    Set-Content -LiteralPath (Join-Path $agentsDir "$($a.Name).toml") -Value $toml -Encoding utf8 -NoNewline
  }

  foreach ($c in (Get-CommandFiles -Repo $Repo)) {
    $agent = Get-CommandAgent -Path $c.Path
    if (-not $agent) { continue }
    $task = Get-CommandTask -Path $c.Path
    $skillDesc = Get-CommandSkillDescription -Path $c.Path -CommandName $c.Name -AgentName $agent
    $displayName = Get-DisplayAgentName -Name $agent
    $generated = "<!-- generated by ``$syncCommand``; source: commands/$($c.Name).md. Do not edit here; edit the source and re-run ``$syncCommand`` -->"

    if ($c.Name -eq 'e2e' -or $c.Name -eq 'e2e-resume') {
      $prompt = "---`n" +
                "description: Run this pipeline yourself in the current conversation (do not spawn $displayName)`n" +
                "---`n`n" +
                $generated + "`n`n" +
                "**YOU** run this pipeline in the **current** conversation. Do **not** spawn an ``$agent`` subagent, do not fork a second E2E brain, and do not re-invoke ``/e2e`` or ``/e2e-resume``.`n`n" +
                $task + "`n"
    }
    else {
      $prompt = "---`n" +
                "description: Run the $displayName custom agent for the current request`n" +
                "---`n`n" +
                $generated + "`n`n" +
                "Spawn the ``$agent`` custom agent to handle the current request.`n" +
                "Give it the relevant conversation and repository context plus this task guidance:`n`n" +
                $task + "`n`n" +
                "Wait for the agent to finish, then return its result without redoing its work.`n"
    }
    Set-Content -LiteralPath (Join-Path $promptsDir "$($c.Name).md") -Value $prompt -Encoding utf8 -NoNewline

    $skillMention = '$' + $c.Name
    $displayCommand = (Get-Culture).TextInfo.ToTitleCase(($c.Name -replace '-', ' '))
    $shortDesc = $skillDesc
    if ($shortDesc.Length -gt 180) { $shortDesc = $shortDesc.Substring(0, 177) + '...' }
    $skillDir = Join-Path $skillsRoot $c.Name
    $skillAgentDir = Join-Path $skillDir 'agents'
    New-Item -ItemType Directory -Path $skillAgentDir -Force | Out-Null
    $openaiYaml = "interface:`n" +
                  "  display_name: `"$displayCommand`"`n" +
                  "  short_description: `"$($shortDesc -replace '"', '\"')`"`n" +
                  "  default_prompt: `"Use $skillMention to run the $($c.Name) workflow.`"`n"
    Set-Content -LiteralPath (Join-Path $skillAgentDir 'openai.yaml') -Value $openaiYaml -Encoding utf8 -NoNewline
  }

  Install-PlaybookSkillsTo -SkillsRoot $skillsRoot -Repo $Repo -SyncCommand $syncCommand -HarnessLabel 'codex' -Global | Out-Null
}

function Compare-DirTree {
  # Generic expected-vs-live diff, shared by every harness root below (DRY).
  # Never writes to $LiveRoot. Scoped to $Subpaths only (e.g. agents/,
  # commands/, skills/) rather than the whole live root: ~/.claude, ~/.codex,
  # etc. also hold unrelated harness runtime state (caches, credentials,
  # backups, session/file-history, daemon sockets) that this projection never
  # generates and has no opinion on. Walking the whole tree would report
  # thousands of irrelevant "STALE" entries for files verify-sync has no
  # business flagging, defeating the point of a drift report (D12).
  param([string]$ExpectedRoot, [string]$LiveRoot, [string[]]$Subpaths)
  if (-not (Test-Path -LiteralPath $LiveRoot)) {
    return [pscustomobject]@{ Status = 'NOT INSTALLED'; Drift = @() }
  }
  $drift = New-Object System.Collections.Generic.List[string]
  foreach ($sub in $Subpaths) {
    $expDir = Join-Path $ExpectedRoot $sub
    $liveDir = Join-Path $LiveRoot $sub
    $expRel = if (Test-Path -LiteralPath $expDir) {
      $expNorm = Normalize-Path -Path (Resolve-Path -LiteralPath $expDir).Path
      @(Get-ChildItem -LiteralPath $expDir -Recurse -File | ForEach-Object { Join-Path $sub ($_.FullName.Substring($expNorm.Length).TrimStart('\', '/')) })
    } else { @() }
    $liveRel = if (Test-Path -LiteralPath $liveDir) {
      $liveNorm = Normalize-Path -Path (Resolve-Path -LiteralPath $liveDir).Path
      @(Get-ChildItem -LiteralPath $liveDir -Recurse -File | ForEach-Object { Join-Path $sub ($_.FullName.Substring($liveNorm.Length).TrimStart('\', '/')) })
    } else { @() }
    foreach ($rel in (@($expRel) + @($liveRel) | Sort-Object -Unique)) {
      $e = Join-Path $ExpectedRoot $rel
      $l = Join-Path $LiveRoot $rel
      $eExists = Test-Path -LiteralPath $e
      $lExists = Test-Path -LiteralPath $l
      if ($eExists -and -not $lExists) { $drift.Add("MISSING (expected, not live): $rel") }
      elseif (-not $eExists -and $lExists) { $drift.Add("STALE (live only, not expected): $rel") }
      else {
        $ec = Get-Content -Raw -LiteralPath $e
        $lc = Get-Content -Raw -LiteralPath $l
        if ($ec -ne $lc) { $drift.Add("CHANGED: $rel") }
      }
    }
  }
  $status = if ($drift.Count -eq 0) { 'IN SYNC' } else { 'DRIFT' }
  return [pscustomobject]@{ Status = $status; Drift = @($drift) }
}

$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("verify-sync-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $tempRoot -Force | Out-Null
$exitCode = 0

try {
  $homeDir = [Environment]::GetFolderPath('UserProfile')
  $roots = [ordered]@{
    'claude (~/.claude)' = @{ Expected = Join-Path $tempRoot 'claude'; Live = Join-Path $homeDir '.claude'; Subpaths = @('agents', 'commands', 'skills'); Build = { param($e) Build-ClaudeGlobalExpectedTree -Repo $Repo -Root $e } }
    'grok (~/.grok)'     = @{ Expected = Join-Path $tempRoot 'grok';   Live = Join-Path $homeDir '.grok';   Subpaths = @('skills');                       Build = { param($e) Build-GrokGlobalExpectedTree -Repo $Repo -Root $e } }
  }

  # Codex writes two live roots from one build step; build once, compare twice.
  $codexExpected = Join-Path $tempRoot 'codex'
  $agentsExpected = Join-Path $tempRoot 'agents'
  Build-CodexGlobalExpectedTrees -Repo $Repo -CodexRoot $codexExpected -AgentsRoot $agentsExpected
  $roots['codex (~/.codex)'] = @{ Expected = $codexExpected; Live = (Join-Path $homeDir '.codex'); Subpaths = @('agents', 'prompts') }
  $roots['agents (~/.agents)'] = @{ Expected = $agentsExpected; Live = (Join-Path $homeDir '.agents'); Subpaths = @('skills') }

  foreach ($label in $roots.Keys) {
    $r = $roots[$label]
    if ($r.Build) { & $r.Build $r.Expected }
    $result = Compare-DirTree -ExpectedRoot $r.Expected -LiveRoot $r.Live -Subpaths $r.Subpaths
    if ($result.Status -eq 'DRIFT') {
      Write-Host "$label`: DRIFT"
      foreach ($d in $result.Drift) { Write-Host "  $d" }
      $exitCode = 1
    }
    else {
      Write-Host "$label`: $($result.Status)"
    }
  }
}
finally {
  Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
}

exit $exitCode
