param()
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"
$Repo = Get-RepoRoot

<#
  make verify-sync (D12, task 1.6) — drift detector for the four PERSONAL
  ("-Global") harness projections: ~/.claude, ~/.grok, ~/.codex, ~/.agents
  (Codex's global skills root). Regenerates each harness's expected file set
  into an isolated temp root, diffs it against the live tree, and prints
  IN SYNC / DRIFT / NOT INSTALLED per root. Exits non-zero iff any root shows
  real DRIFT. Strictly read-only w.r.t. the operator's home (I5): every write
  in this script targets the temp root only; live trees are only ever read.

  Why this script re-derives each harness's Global output instead of shelling
  out to claude.ps1/grok.ps1/codex.ps1 -Global (which would be more DRY): on
  Windows, [Environment]::GetFolderPath('UserProfile') resolves via the OS
  profile registry, not the USERPROFILE env var — verified empirically (a
  child process launched with USERPROFILE overridden still reports the real
  profile path). There is no supported way to redirect a -Global installer's
  root to a temp directory from the outside, and install/<harness>.ps1 are
  each owned by a later wave (plan.v3.md section 1.4a) so wave-1 cannot
  restructure them to accept an override parameter. The functions below
  therefore mirror each installer's current Global-mode body construction
  using the SAME shared common.ps1 primitives those installers call — only
  the harness-specific glue (folder layout, TOML/prompt assembly) is
  duplicated. If a later wave changes that glue, this file must be updated in
  lockstep; that coupling is intentional and disclosed, not hidden.
#>

function Get-CodexSandboxModeMirror {
  # Mirrors install/codex.ps1's Get-CodexSandboxMode (wave-3-owned).
  param([string]$Name)
  switch ($Name) {
    'builder'      { return 'workspace-write' }
    'qa'           { return 'workspace-write' }
    'orchestrator' { return 'workspace-write' }
    default        { return 'read-only' }
  }
}

function Escape-TomlBasicStringMirror {
  # Mirrors install/codex.ps1's Escape-TomlBasicString (wave-3-owned).
  param([string]$s)
  return ($s -replace '\\', '\\' -replace '"', '\"')
}

function ConvertTo-TomlDeveloperInstructionsBlockMirror {
  # Mirrors install/codex.ps1's ConvertTo-TomlDeveloperInstructionsBlock
  # (wave-3-owned, task 3.5's round-trip fidelity fix). Found stale during
  # wave-7 task 7.0/7.6a: this mirror still used the pre-3.5 raw '''...'''
  # embed with no fallback, which wave-3's own report flagged as a live risk
  # the moment ConvertTo-TomlDeveloperInstructionsBlock's behavior changed.
  # It did change (that was task 3.5's entire point), so this was reported as
  # real DRIFT for every codex/*.toml file against the actual, correct,
  # freshly-`install-codex-global`-synced live install — confirmed a false
  # positive by diffing a live file against a fresh temp-target regeneration
  # byte-for-byte before this fix. Fixed by mirroring the real function.
  param([string]$Content)
  $needsBasicString = ($Content -match "'''") -or $Content.EndsWith("'")
  if (-not $needsBasicString) {
    return "'''`n$Content" + "'''"
  }
  $escaped = Escape-TomlBasicStringMirror -s $Content
  return '"""' + "`n$escaped" + '"""'
}

function Build-ClaudeGlobalExpectedTree {
  # Mirrors install/claude.ps1's -Global branch (wave-2-owned).
  param([string]$Repo, [string]$Root)
  $syncCommand = 'make sync-claude-global'
  $agentsDir = Join-Path $Root 'agents'
  $cmdsDir = Join-Path $Root 'commands'
  $skillsRoot = Join-Path $Root 'skills'
  New-Item -ItemType Directory -Path $agentsDir, $cmdsDir, $skillsRoot -Force | Out-Null

  foreach ($a in (Get-AgentFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
    $desc = Get-AgentDescription -Path $a.Path
    $header = "<!-- generated by ``$syncCommand``; source: agents/$($a.Name).md. Do not edit here; edit agents/$($a.Name).md and re-run: $syncCommand -->"
    $fm = Get-ClaudeAgentFrontmatter -Name $a.Name -Description $desc
    $body = "$fm`n`n$header`n`n$content`n"
    Set-Content -LiteralPath (Join-Path $agentsDir "$($a.Name).md") -Value $body -Encoding utf8 -NoNewline
  }

  foreach ($c in (Get-CommandFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $c.Path).TrimEnd()
    $header = "<!-- generated by ``$syncCommand``; source: commands/$($c.Name).md -->"
    $agent = Get-CommandAgent -Path $c.Path
    $task = Get-CommandTask -Path $c.Path
    $agentForDesc = if ($agent) { $agent } else { 'agent' }
    $skillDesc = Get-CommandSkillDescription -Path $c.Path -CommandName $c.Name -AgentName $agentForDesc
    # Mirrors install/claude.ps1's wave-2 fix (F-2/D3, disclosed by wave-1,
    # fixed wave-2): name the role, never bake this machine's absolute repo
    # path into a generated artifact. This mirror is a -Global build, so the
    # role-fallback hint always uses the -Global phrasing.
    $roleHint = "ask which project's canonical ``agents/$agentForDesc.md`` to load (a personal/global install is not tied to one specific repo checkout)"
    $cmdBody = @"
---
description: $skillDesc
---

$header

$task

Load the ``$agentForDesc`` specialist by name (Claude subagent or skill) when available; otherwise $roleHint. Prefer the installed skill ``/$($c.Name)`` and subagents under the Claude agents directory when available.
"@
    Set-Content -LiteralPath (Join-Path $cmdsDir "$($c.Name).md") -Value $cmdBody -Encoding utf8 -NoNewline
  }

  Install-PlaybookSkillsTo -SkillsRoot $skillsRoot -Repo $Repo -SyncCommand $syncCommand -HarnessLabel 'claude' -Global | Out-Null

  # Mirrors install/claude.ps1's wave-2 task 2.5 post-patch: e2e/e2e-resume
  # alone get argument-hint + disable-model-invocation, regenerated
  # individually over the uniform-frontmatter copy Install-PlaybookSkillsTo
  # just wrote (see install/claude.ps1 for the full rationale).
  foreach ($cmdName in @('e2e', 'e2e-resume')) {
    $cmdPath = Join-Path $Repo "commands\$cmdName.md"
    if (-not (Test-Path -LiteralPath $cmdPath)) { continue }
    $agent = Get-CommandAgent -Path $cmdPath
    $task = Get-CommandTask -Path $cmdPath
    $skillDesc = Get-CommandSkillDescription -Path $cmdPath -CommandName $cmdName -AgentName $agent
    $argHint = Get-CommandArgumentHint -Path $cmdPath
    $extraFrontmatter = [ordered]@{}
    if ($argHint) { $extraFrontmatter['argument-hint'] = $argHint }
    $extraFrontmatter['disable-model-invocation'] = 'true'
    $skill = New-PlaybookSkillMarkdown `
      -CommandName $cmdName `
      -AgentName $agent `
      -Task $task `
      -SkillDescription $skillDesc `
      -SyncCommand $syncCommand `
      -Repo $Repo `
      -Global `
      -ExtraFrontmatter $extraFrontmatter
    Set-Content -LiteralPath (Join-Path $skillsRoot "$cmdName\SKILL.md") -Value $skill -Encoding utf8 -NoNewline
  }
}

function Build-GrokGlobalExpectedTree {
  # Mirrors install/grok.ps1's -Global branch (wave-5-owned).
  # task 5.5 (F-9) deleted the dead `_playbook-agents` reference dump from the
  # real installer (Grok never loaded it; role definitions are read via Claude
  # Code compatibility instead — see adapters/grok.md). This mirror still
  # generated it until wave-7 task 7.0/7.6a found the resulting false DRIFT
  # against the real, correctly-5.5'd live install (every _playbook-agents/*
  # file reported MISSING because the live install correctly no longer writes
  # it) — fixed by matching the real installer exactly: skills only.
  param([string]$Repo, [string]$Root)
  $syncCommand = 'make sync-grok-global'
  $skillsRoot = Join-Path $Root 'skills'
  New-Item -ItemType Directory -Path $skillsRoot -Force | Out-Null
  Install-PlaybookSkillsTo -SkillsRoot $skillsRoot -Repo $Repo -SyncCommand $syncCommand -HarnessLabel 'grok' -Global | Out-Null
}

function Build-CodexGlobalExpectedTrees {
  # Mirrors install/codex.ps1's -Global branch (wave-3-owned).
  param([string]$Repo, [string]$CodexRoot, [string]$AgentsRoot)
  $syncCommand = 'make sync-codex-global'
  $agentsDir = Join-Path $CodexRoot 'agents'
  $promptsDir = Join-Path $CodexRoot 'prompts'
  $skillsRoot = Join-Path $AgentsRoot 'skills'
  New-Item -ItemType Directory -Path $agentsDir, $promptsDir, $skillsRoot -Force | Out-Null

  foreach ($a in (Get-AgentFiles -Repo $Repo)) {
    $content = (Get-Content -Raw -LiteralPath $a.Path).TrimEnd()
    $desc = Get-AgentDescription -Path $a.Path
    $sandbox = Get-CodexSandboxModeMirror -Name $a.Name
    $descEsc = Escape-TomlBasicStringMirror -s $desc
    # task 3.1: reasoning effort is sourced from Get-RoleMeta's effortLevel,
    # same single derivation the real installer uses (never hand-picked).
    $reasoningEffort = (Get-RoleMeta -Name $a.Name).effortLevel
    $instructionsBlock = ConvertTo-TomlDeveloperInstructionsBlockMirror -Content $content
    $header = "# generated by '$syncCommand'; source: agents/$($a.Name).md" + "`n" +
              "# Do not edit here; edit agents/$($a.Name).md and re-run: $syncCommand" + "`n" +
              "# model left unset: no per-harness model ID pinned yet (plan.v3.md section 4, open decision 6)."
    $toml = $header + "`n`n" +
            "name = `"$($a.Name)`"" + "`n" +
            "description = `"$descEsc`"" + "`n" +
            "model = `"`"" + "`n" +
            "model_reasoning_effort = `"$reasoningEffort`"" + "`n" +
            "sandbox_mode = `"$sandbox`"" + "`n" +
            "developer_instructions = " + $instructionsBlock + "`n"
    Set-Content -LiteralPath (Join-Path $agentsDir "$($a.Name).toml") -Value $toml -Encoding utf8 -NoNewline
  }

  # task 3.3/F-12: deprecation banner on every generated prompt. Also missing
  # from this mirror until wave-7 task 7.0/7.6a found it (same staleness class
  # as the developer_instructions embedding above).
  $deprecationNote = '> **Deprecated:** this custom-prompt surface (`~/.codex/prompts/*.md`, invoked as `/prompts:<name>`) is deprecated by Codex in favor of skills; kept for one more cycle. Removal is an open decision for Juan — see `adapters/codex.md`.'

  foreach ($c in (Get-CommandFiles -Repo $Repo)) {
    $agent = Get-CommandAgent -Path $c.Path
    if (-not $agent) { continue }
    $task = Get-CommandTask -Path $c.Path
    $skillDesc = Get-CommandSkillDescription -Path $c.Path -CommandName $c.Name -AgentName $agent
    $displayName = Get-DisplayAgentName -Name $agent
    $generated = "<!-- generated by ``$syncCommand``; source: commands/$($c.Name).md. Do not edit here; edit the source and re-run ``$syncCommand`` -->"

    if ($c.Name -eq 'e2e' -or $c.Name -eq 'e2e-resume') {
      $prompt = "---`n" +
                "description: Run this pipeline yourself in the current conversation (do not spawn $displayName)`n" +
                "---`n`n" +
                $generated + "`n`n" +
                $deprecationNote + "`n`n" +
                "**YOU** run this pipeline in the **current** conversation. Do **not** spawn an ``$agent`` subagent, do not fork a second E2E brain, and do not re-invoke ``/e2e`` or ``/e2e-resume``.`n`n" +
                $task + "`n"
    }
    else {
      $prompt = "---`n" +
                "description: Run the $displayName custom agent for the current request`n" +
                "---`n`n" +
                $generated + "`n`n" +
                $deprecationNote + "`n`n" +
                "Spawn the ``$agent`` custom agent to handle the current request.`n" +
                "Give it the relevant conversation and repository context plus this task guidance:`n`n" +
                $task + "`n`n" +
                "Wait for the agent to finish, then return its result without redoing its work.`n"
    }
    Set-Content -LiteralPath (Join-Path $promptsDir "$($c.Name).md") -Value $prompt -Encoding utf8 -NoNewline

    $skillMention = '$' + $c.Name
    $displayCommand = (Get-Culture).TextInfo.ToTitleCase(($c.Name -replace '-', ' '))
    $shortDesc = $skillDesc
    if ($shortDesc.Length -gt 180) { $shortDesc = $shortDesc.Substring(0, 177) + '...' }
    $skillDir = Join-Path $skillsRoot $c.Name
    $skillAgentDir = Join-Path $skillDir 'agents'
    New-Item -ItemType Directory -Path $skillAgentDir -Force | Out-Null
    $openaiYaml = "interface:`n" +
                  "  display_name: `"$displayCommand`"`n" +
                  "  short_description: `"$($shortDesc -replace '"', '\"')`"`n" +
                  "  default_prompt: `"Use $skillMention to run the $($c.Name) workflow.`"`n"
    Set-Content -LiteralPath (Join-Path $skillAgentDir 'openai.yaml') -Value $openaiYaml -Encoding utf8 -NoNewline
  }

  Install-PlaybookSkillsTo -SkillsRoot $skillsRoot -Repo $Repo -SyncCommand $syncCommand -HarnessLabel 'codex' -Global | Out-Null
}

function Compare-DirTree {
  # Generic expected-vs-live diff, shared by every harness root below (DRY).
  # Never writes to $LiveRoot. Scoped to $Subpaths only (e.g. agents/,
  # commands/, skills/) rather than the whole live root: ~/.claude, ~/.codex,
  # etc. also hold unrelated harness runtime state (caches, credentials,
  # backups, session/file-history, daemon sockets) that this projection never
  # generates and has no opinion on. Walking the whole tree would report
  # thousands of irrelevant "STALE" entries for files verify-sync has no
  # business flagging, defeating the point of a drift report (D12).
  param([string]$ExpectedRoot, [string]$LiveRoot, [string[]]$Subpaths)
  if (-not (Test-Path -LiteralPath $LiveRoot)) {
    return [pscustomobject]@{ Status = 'NOT INSTALLED'; Drift = @() }
  }
  $drift = New-Object System.Collections.Generic.List[string]
  foreach ($sub in $Subpaths) {
    $expDir = Join-Path $ExpectedRoot $sub
    $liveDir = Join-Path $LiveRoot $sub
    $expRel = if (Test-Path -LiteralPath $expDir) {
      $expNorm = Normalize-Path -Path (Resolve-Path -LiteralPath $expDir).Path
      @(Get-ChildItem -LiteralPath $expDir -Recurse -File | ForEach-Object { Join-Path $sub ($_.FullName.Substring($expNorm.Length).TrimStart('\', '/')) })
    } else { @() }
    $liveRel = if (Test-Path -LiteralPath $liveDir) {
      $liveNorm = Normalize-Path -Path (Resolve-Path -LiteralPath $liveDir).Path
      @(Get-ChildItem -LiteralPath $liveDir -Recurse -File | ForEach-Object { Join-Path $sub ($_.FullName.Substring($liveNorm.Length).TrimStart('\', '/')) })
    } else { @() }
    foreach ($rel in (@($expRel) + @($liveRel) | Sort-Object -Unique)) {
      $e = Join-Path $ExpectedRoot $rel
      $l = Join-Path $LiveRoot $rel
      $eExists = Test-Path -LiteralPath $e
      $lExists = Test-Path -LiteralPath $l
      if ($eExists -and -not $lExists) { $drift.Add("MISSING (expected, not live): $rel") }
      elseif (-not $eExists -and $lExists) { $drift.Add("STALE (live only, not expected): $rel") }
      else {
        $ec = Get-Content -Raw -LiteralPath $e
        $lc = Get-Content -Raw -LiteralPath $l
        if ($ec -ne $lc) { $drift.Add("CHANGED: $rel") }
      }
    }
  }
  $status = if ($drift.Count -eq 0) { 'IN SYNC' } else { 'DRIFT' }
  return [pscustomobject]@{ Status = $status; Drift = @($drift) }
}

$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("verify-sync-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $tempRoot -Force | Out-Null
$exitCode = 0

try {
  $homeDir = [Environment]::GetFolderPath('UserProfile')
  $roots = [ordered]@{
    'claude (~/.claude)' = @{ Expected = Join-Path $tempRoot 'claude'; Live = Join-Path $homeDir '.claude'; Subpaths = @('agents', 'commands', 'skills'); Build = { param($e) Build-ClaudeGlobalExpectedTree -Repo $Repo -Root $e } }
    'grok (~/.grok)'     = @{ Expected = Join-Path $tempRoot 'grok';   Live = Join-Path $homeDir '.grok';   Subpaths = @('skills');                       Build = { param($e) Build-GrokGlobalExpectedTree -Repo $Repo -Root $e } }
  }

  # Codex writes two live roots from one build step; build once, compare twice.
  $codexExpected = Join-Path $tempRoot 'codex'
  $agentsExpected = Join-Path $tempRoot 'agents'
  Build-CodexGlobalExpectedTrees -Repo $Repo -CodexRoot $codexExpected -AgentsRoot $agentsExpected
  $roots['codex (~/.codex)'] = @{ Expected = $codexExpected; Live = (Join-Path $homeDir '.codex'); Subpaths = @('agents', 'prompts') }
  $roots['agents (~/.agents)'] = @{ Expected = $agentsExpected; Live = (Join-Path $homeDir '.agents'); Subpaths = @('skills') }

  foreach ($label in $roots.Keys) {
    $r = $roots[$label]
    if ($r.Build) { & $r.Build $r.Expected }
    $result = Compare-DirTree -ExpectedRoot $r.Expected -LiveRoot $r.Live -Subpaths $r.Subpaths
    if ($result.Status -eq 'DRIFT') {
      Write-Host "$label`: DRIFT"
      foreach ($d in $result.Drift) { Write-Host "  $d" }
      $exitCode = 1
    }
    else {
      Write-Host "$label`: $($result.Status)"
    }
  }
}
finally {
  Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
}

exit $exitCode
